### ISSUE TITLE
Provinces and municipalities in the registration form

### ISSUE THREAD

**Issue by aligys** [mepawan/dovecercare_beta#1]
Hi, As you can see in the other form there are the provinces and municipalities. So when the user'll select Italy and then select the province (city) you should make see the municipalities. They are already divided per provinces.
I think should something similar also for the others country.
Regards
Gaetano

**Comment by mepawan** [comment]
Fixed. We are now using all countries province(state) database. Old Municipalities tatabse table was synced with your old province table. Its taken lot of time to sync Municipalities table with new provice table. But finaly done :)
